### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by YL-ZZZ** [alga-hopf/drl-graph-partitioning#2]
There are several required  software listed in readme, but not specify the versions of them. Is there a requirement.txt file for installation?

**Comment by alga-hopf** [comment]
The requirements.txt is available now, please check also the "Required software" section in the README. I will also write how to build the additional software. However, I found a couple of problems when running Scotch and AMD. I'm looking into that.

**Comment by YL-ZZZ** [comment]
May I know the python version you use.

**Comment by alga-hopf** [comment]
3.10.12

**Comment by alga-hopf** [comment]
The issues with Scotch and AMD should be solved. I hope the code works now.
