### ISSUE TITLE
Dependency installation problems

### ISSUE THREAD

**Issue by xiong-zx** [alga-hopf/drl-graph-partitioning#3]
I would like to use your vertex separation algorithm for my project. I want to run your code, but the package `networkx-metis` seems outdated and I cannot install it either by PyPI or from the source. Could you please provide some information regarding how to install `networkx-metis` as well as `AMD` and `Scotch`?

**Comment by alga-hopf** [comment]
Please install networkx-metis following the instruction on the [networkx-metis webpage](https://networkx-metis.readthedocs.io/en/latest/install.html), "Installing from source" and then "Github". I had issues with installing AMD and Scotch, which I am trying to solve.

**Comment by alga-hopf** [comment]
The issues with Scotch should be solved. I hope the code works now.

**Comment by xiong-zx** [comment]
Could you please provide the details of the cython and network-metis version? I tried to install network-metis on my Ubuntu machine, but error occurred when compiling cython file. (I am using cython 3.0.5)

**Comment by alga-hopf** [comment]
Cython version is 0.29.28, nxmetis is the latest development from github
